//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20._101_Gladunov_authorization.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IDUser { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IDRole { get; set; }
    
        public virtual Roles Roles { get; set; }
        public string GetNameRole { get; internal set; }
    }
}
